routes/web.php
<?php

use App\Http\Controllers\Dashboard;
use App\Http\Controllers\Home;

Route::get('/', Home::class)->name('home');
Route::get('/dashboard', Dashboard::class)->name('dashboard')->middleware('auth');


Route::resource('dosen', '\App\Http\Controllers\DosenController');
Route::resource('mahasiswa', '\App\Http\Controllers\MahasiswaController');
Route::resource('matakuliah', '\App\Http\Controllers\MataKuliahController');
Route::resource('matakuliah', '\App\Http\Controllers\MataKuliahController');
Route::resource('pendaftaranmatakuliah', '\App\Http\Controllers\PendaftaraMataKuliahController');

app/Models/Dosen.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;

class Dosen extends Model
{
    use HasFactory;
    
    protected $table = 'dosen';
    protected $primaryKey = 'id';
    protected $fillable = ['nama','nip','gelar'];
    public $timestamps = false;

    public function riwayatPendidikan(){
    //setiap profil memiliki satu mahasiswa
    return $this->hasMany(RiwayatPendidikan::class);
  }

    public function dosen_mata_kuliah() {
        return $this->hasMany(DosenMataKuliah::class);
    }

}

app/Http/Controllers/DosenController.php
<?php

namespace App\Http\Controllers;

use Illuminate\Http\Request;
use App\Models\Dosen;
use DB;

class DosenController extends Controller
{
     public function index()
    {
        $dosens = Dosen::latest()->paginate(10);
        // dd($dosens);
        return view('dosen.index', compact('dosens'));
    }

    public function show($id)
	{
		// get the nerd
		$dosens = Dosen::with('riwayatPendidikan')->find($id);
        //  dd($dosens);
		// show the view and pass the nerd to it
		return view('dosen.show', compact('dosens'));
	}

    public function create()
    {
        return view('dosen.create');
    }

    public function store(Request $request)
    {

        // dd($request->all());
        $this->validate($request, [
            'nama'    => 'required',
            'nip'     => 'required',
            'gelar'   => 'required',
            'strata'  => 'required',
            'jurusan' => 'required',
            'sekolah' => 'required',
            'tahun_mulai'=> 'required',
            'tahun_selesai' => 'required'
        ]);


        $dosen = Dosen::create([
            'nama'     => $request->nama,
            'nip'     => $request->nip,
            'gelar'   => $request->gelar
        ]);

        $dosen_id = $dosen->id;
        $strata = $request->strata;
        $jurusan = $request->jurusan;
        $sekolah = $request->sekolah;
        $tahun_mulai = $request->tahun_mulai;
        $tahun_selesai = $request->tahun_selesai;

        for($i=0; $i < count($strata); $i++){
            $datasave = [
                'dosen_id' => $dosen_id,
                'strata'  => $strata[$i],
                'jurusan' => $jurusan[$i],
                'sekolah' => $sekolah[$i],
                'tahun_mulai'=> $tahun_mulai[$i],
                'tahun_selesai' => $tahun_selesai[$i]
            ];
           $save = DB::table('riwayat_pendidikan')->insert($datasave);
        }

        // return redirect()->route('dosen.index')->with(['success' => 'Data Berhasil Disimpan!']);
        if($dosen && $save){
            //redirect dengan pesan sukses
            return redirect()->route('dosen.index')->with(['success' => 'Data Berhasil Disimpan!']);
        }else{
            //redirect dengan pesan error
            return redirect()->route('dosen.index')->with(['error' => 'Data Gagal Disimpan!']);
        }
    }

}

resources/views/dosen/create.blade.php
<!DOCTYPE html>
<html>
<head>
    <title>Add/remove multiple input fields dynamically with Jquery Laravel 5.8</title>
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.6/css/bootstrap.min.css" />  
    <script src="//ajax.googleapis.com/ajax/libs/jquery/1.12.4/jquery.min.js"></script>
</head>
<body>
   
<div class="container">
    <h2 align="center">Masukan Data Dosen</h2> 
   
    <form action="{{ route('dosen.store') }}" method="POST">
        @csrf
        @if ($errors->any())
            <div class="alert alert-danger">
                <ul>
                    @foreach ($errors->all() as $error)
                        <li>{{ $error }}</li>
                    @endforeach
                </ul>
            </div>
        @endif
   
        @if (Session::has('success'))
            <div class="alert alert-success text-center">
                <a href="#" class="close" data-dismiss="alert" aria-label="close">×</a>
                <p>{{ Session::get('success') }}</p>
            </div>
        @endif
        
                            <div class="form-group">
                                <label class="font-weight-bold">Nama</label>
                                <input type="text" class="form-control @error('nama') is-invalid @enderror" name="nama" value="{{ old('nama') }}" placeholder="Masukkan Nama">
                            
                                <!-- error message untuk title -->
                                @error('title')
                                    <div class="alert alert-danger mt-2">
                                        {{ $message }}
                                    </div>
                                @enderror
                            </div>

                            <div class="form-group">
                                <label class="font-weight-bold">NIP</label>
                                <input type="number" class="form-control @error('number') is-invalid @enderror" name="nip" value="{{ old('nip') }}" placeholder="Masukkan Nip">
                            
                                <!-- error message untuk title -->
                                @error('title')
                                    <div class="alert alert-danger mt-2">
                                        {{ $message }}
                                    </div>
                                @enderror
                            </div>

                            <div class="form-group">
                                <label class="font-weight-bold">GELAR</label>
                                <input type="text" class="form-control @error('gelar') is-invalid @enderror" name="gelar" value="{{ old('gelar') }}" placeholder="Masukkan Gelar">
                            
                                <!-- error message untuk title -->
                                @error('title')
                                    <div class="alert alert-danger mt-2">
                                        {{ $message }}
                                    </div>
                                @enderror
                            </div>
        <table class="table table-bordered" id="dynamicTable">  
            <tr>
                <th>Strata</th>
                <th>Jurusan</th>
                <th>Sekolah</th>
                <th>Tahun Mulai</th>
                <th>Tahun Selesai</th>
                <th>Action</th>
            </tr>
            <tr>  
                <td><input type="number" name="strata[]" placeholder="Masukan Tingkat Strata" class="form-control" /></td>  
                <td><input type="text" name="jurusan[]" placeholder="Masukan Jurusan" class="form-control" /></td>  
                <td><input type="text" name="sekolah[]" placeholder="Masukan Nama Sekolah" class="form-control" /></td>
                 <td><input type="text" name="tahun_mulai[]" placeholder="Tahun Mulai" class="form-control" /></td>
                  <td><input type="text" name="tahun_selesai[]" placeholder="Tahun Selesai" class="form-control" /></td>
                  
                <td><button type="button" name="add" id="add" class="btn btn-success">Add More</button></td>  
            </tr>  
        </table> 
         <button type="submit" class="btn btn-success">Save</button>
    </form>
</div>
   
<script type="text/javascript">
   
    var i = 0;
       
    $("#add").click(function(){
   
        ++i;
   
        $("#dynamicTable").append('<tr><td><input type="number" name="strata[]" placeholder="Masukan Tingkat Strata" class="form-control" /></td><td><input type="text" name="jurusan[]" placeholder="Masukan Jurusan" class="form-control" /></td><td><input type="text" name="sekolah[]" placeholder="Masukan Nama Sekolah" class="form-control" /></td><td><input type="text" name="tahun_mulai[]" placeholder="Tahun Mulai" class="form-control" /></td><td><input type="text" name="tahun_selesai[]" placeholder="Tahun Selesai" class="form-control" /></td><td><button type="button" class="btn btn-danger remove-tr">Remove</button></td></tr>');
    });
   
    $(document).on('click', '.remove-tr', function(){  
         $(this).parents('tr').remove();
    });  
   
</script>
  
</body>
</html>

resources/views/dosen/index.blade.php
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <title>Data Dosen - Javan Solution</title>
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/css/bootstrap.min.css">
    <link rel="stylesheet" href="//cdnjs.cloudflare.com/ajax/libs/toastr.js/latest/toastr.min.css">
</head>
<body style="background: lightgray">

    <div class="container mt-5">
        <div class="row">
            <div class="col-md-12">
                <div class="card border-0 shadow rounded">
                    <div class="card-body">
                        <a href="{{ route('dosen.create') }}" class="btn btn-md btn-success mb-3">TAMBAH Dosen</a>
                        <table class="table table-bordered">
                            <thead>
                              <tr>
                                <th scope="col">Nama</th>
                                <th scope="col">Nip</th>
                                <th scope="col">Gelar</th>
                                <th scope="col">AKSI</th>
                              </tr>
                            </thead>
                            <tbody>
                              @forelse ($dosens as $dosen)
                                <tr>
                                    <td>{{ $dosen->nama }}</td>
                                    <td>{{ $dosen->nip }}</td>
                                    <td>{{ $dosen->gelar }}</td>
                                    <td class="text-center">
                                        <form onsubmit="return confirm('Apakah Anda Yakin ?');" action="{{ route('dosen.destroy', $dosen->id) }}" method="POST">
                                            <a href="{{ route('dosen.show', $dosen->id) }}" class="btn btn-sm btn-primary">Show</a>
                                            <a href="{{ route('dosen.edit', $dosen->id) }}" class="btn btn-sm btn-primary">EDIT</a>
                                            @csrf
                                            @method('DELETE')
                                            <button type="submit" class="btn btn-sm btn-danger">HAPUS</button>
                                        </form>
                                    </td>
                                </tr>
                              @empty
                                  <div class="alert alert-danger">
                                      Data Dosen belum Tersedia.
                                  </div>
                              @endforelse
                            </tbody>
                          </table>  
                          {{ $dosens->links() }}
                    </div>
                </div>
            </div>
        </div>
    </div>
    
    <script src="https://cdnjs.cloudflare.com/ajax/libs/jquery/3.5.1/jquery.min.js"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/js/bootstrap.min.js"></script>
    <script src="//cdnjs.cloudflare.com/ajax/libs/toastr.js/latest/toastr.min.js"></script>

    <script>
        //message with toastr
        @if(session()->has('success'))
        
            toastr.success('{{ session('success') }}', 'BERHASIL!'); 

        @elseif(session()->has('error'))

            toastr.error('{{ session('error') }}', 'GAGAL!'); 
            
        @endif
    </script>

</body>
</html>

resources/views/dosen/show.blade.php
<!DOCTYPE html>
<html>
<head>
	<title>Dosen</title>
	<link rel="stylesheet" href="//netdna.bootstrapcdn.com/bootstrap/3.0.0/css/bootstrap.min.css">
</head>
<body>
<div class="container">

<nav class="navbar navbar-inverse">
	<ul class="nav navbar-nav">
		<li><a href="{{ URL::to('dosen') }}">View All Dosen</a></li>
	</ul>
</nav>

<h1>Data Lengkap Dosen</h1>

	<div class="jumbotron text-center">
		<p>Nama : {{$dosens->nama}}</p> 
        <p>Nama : {{$dosens->nip}}</p> 
        <p>Nama : {{$dosens->gelar}}</p> 
        @foreach($dosens->riwayatPendidikan as $dosen)
		<p> Strata : {{ $dosen->strata }}</p>
        <p> Jurusan : {{ $dosen->jurusan }}</p>
        <p> Sekolah : {{ $dosen->sekolah }}</p>
        <p> Sekolah : {{ $dosen->tahun_mulai }}</p>
        <p> Sekolah : {{ $dosen->tahun_selesai }}</p>
        <br>
        @endforeach
	</div>

</div>
</body>
</html>