routes/web.php
<?php

use App\Http\Controllers\Dashboard;
use App\Http\Controllers\Home;

Route::get('/', Home::class)->name('home');
Route::get('/dashboard', Dashboard::class)->name('dashboard')->middleware('auth');


Route::resource('dosen', '\App\Http\Controllers\DosenController');
Route::resource('mahasiswa', '\App\Http\Controllers\MahasiswaController');
Route::resource('matakuliah', '\App\Http\Controllers\MataKuliahController');
Route::resource('matakuliah', '\App\Http\Controllers\MataKuliahController');
Route::resource('pendaftaranmatakuliah', '\App\Http\Controllers\PendaftaraMataKuliahController');

app/Models/MataKuliah.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;

class MataKuliah extends Model
{
    use HasFactory;
    protected $table = 'mata_kuliah';
    protected $primaryKey = 'id';
    protected $fillable = ['nama','sks'];
    public $timestamps = false;

    public function dosen_mata_kuliah() {
        return $this->hasMany(DosenMataKuliah::class);
    }

    public function kelas_mata_kuliah() {
        return $this->hasMany(KelasMataKuliah::class);
    }
    public function pendaftaran_matkul() {
        return $this->hasMany(PendaftaranMatkul::class);
    }

}

app/Http/Controllers/MataKuliahController.php
<?php

namespace App\Http\Controllers;

use Illuminate\Http\Request;
use App\Models\MataKuliah;


class MataKuliahController extends Controller
{
     public function index()
    {
        $matakuliahs = MataKuliah::latest()->paginate(10);
        return view('matakuliah.index', compact('matakuliahs'));
    }

    public function create()
    {
        return view('matakuliah.create');
    }

    public function store(Request $request)
    {

        // dd($request->all());
        $this->validate($request, [
            'nama'    => 'required',
            'sks'     => 'required'

        ]);


        $matakuliah = MataKuliah::create([
            'nama'     => $request->nama,
            'sks'     => $request->sks
        ]);

      
        // return redirect()->route('dosen.index')->with(['success' => 'Data Berhasil Disimpan!']);
        if($matakuliah){
            //redirect dengan pesan sukses
            return redirect()->route('matakuliah.index')->with(['success' => 'Data Berhasil Disimpan!']);
        }else{
            //redirect dengan pesan error
            return redirect()->route('matakuliah.index')->with(['error' => 'Data Gagal Disimpan!']);
        }
    }
}

resources/views/matakuliah/create.blade.php
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <title>Tambah Data Blog - SantriKoding.com</title>
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/css/bootstrap.min.css">
</head>
<body style="background: lightgray">

    <div class="container mt-5 mb-5">
        <div class="row">
            <div class="col-md-12">
                <div class="card border-0 shadow rounded">
                    <div class="card-body">
                        <form action="{{ route('matakuliah.store') }}" method="POST" enctype="multipart/form-data">
                        
                            @csrf
                            <div class="form-group">
                                <label class="font-weight-bold">Nama</label>
                                <input type="text" class="form-control @error('nama') is-invalid @enderror" name="nama" value="{{ old('nama') }}" placeholder="Masukkan MataKuliah">
                            
                                <!-- error message untuk title -->
                                @error('nama')
                                    <div class="alert alert-danger mt-2">
                                        {{ $message }}
                                    </div>
                                @enderror
                            </div>

                            <div class="form-group">
                                <label class="font-weight-bold">SKS</label>
                                <input type="number" class="form-control @error('sks') is-invalid @enderror" name="sks" value="{{ old('nim') }}" placeholder="Masukkan SKS">
                            
                                <!-- error message untuk title -->
                                @error('sks')
                                    <div class="alert alert-danger mt-2">
                                        {{ $message }}
                                    </div>
                                @enderror
                            </div>
                            <button type="submit" class="btn btn-md btn-primary">SIMPAN</button>
                            <button type="reset" class="btn btn-md btn-warning">RESET</button>

                        </form> 
                    </div>
                </div>
            </div>
        </div>
    </div>
    
<script src="https://cdnjs.cloudflare.com/ajax/libs/jquery/3.5.1/jquery.min.js"></script>
<script src="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/js/bootstrap.min.js"></script>
</body>
</html>

resources/views/matakuliah/index.blade.php
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <title>Data MataKuliah - Javan Solution</title>
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/css/bootstrap.min.css">
    <link rel="stylesheet" href="//cdnjs.cloudflare.com/ajax/libs/toastr.js/latest/toastr.min.css">
</head>
<body style="background: lightgray">

    <div class="container mt-5">
        <div class="row">
            <div class="col-md-12">
                <div class="card border-0 shadow rounded">
                    <div class="card-body">
                        <a href="{{ route('matakuliah.create') }}" class="btn btn-md btn-success mb-3">TAMBAH MataKuliah</a>
                        <table class="table table-bordered">
                            <thead>
                              <tr>
                                <th scope="col">Nama</th>
                                <th scope="col">SKS</th>
                                <th scope="col">AKSI</th>
                              </tr>
                            </thead>
                            <tbody>
                              @forelse ($matakuliahs as $matakuliah)
                                <tr>
                                    <td>{{ $matakuliah->nama }}</td>
                                    <td>{{ $matakuliah->sks }}</td>
                                    <td class="text-center">
                                        <form onsubmit="return confirm('Apakah Anda Yakin ?');" action="{{ route('matakuliah.destroy', $matakuliah->id) }}" method="POST">
                                            <a href="{{ route('matakuliah.show', $matakuliah->id) }}" class="btn btn-sm btn-primary">Show</a>
                                            <a href="{{ route('matakuliah.edit', $matakuliah->id) }}" class="btn btn-sm btn-primary">EDIT</a>
                                            @csrf
                                            @method('DELETE')
                                            <button type="submit" class="btn btn-sm btn-danger">HAPUS</button>
                                        </form>
                                    </td>
                                </tr>
                              @empty
                                  <div class="alert alert-danger">
                                      Data Dosen belum Tersedia.
                                  </div>
                              @endforelse
                            </tbody>
                          </table>  
                          {{ $matakuliahs->links() }}
                    </div>
                </div>
            </div>
        </div>
    </div>
    
    <script src="https://cdnjs.cloudflare.com/ajax/libs/jquery/3.5.1/jquery.min.js"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/js/bootstrap.min.js"></script>
    <script src="//cdnjs.cloudflare.com/ajax/libs/toastr.js/latest/toastr.min.js"></script>

    <script>
        //message with toastr
        @if(session()->has('success'))
        
            toastr.success('{{ session('success') }}', 'BERHASIL!'); 

        @elseif(session()->has('error'))

            toastr.error('{{ session('error') }}', 'GAGAL!'); 
            
        @endif
    </script>

</body>
</html>